### ISSUE TITLE
warn: [Entity] Unknown entity type

### ISSUE THREAD

**Issue by danizwam** [breeswish/ingress-exporter#19]
Hi, 

today i got these errors while runnig the script.

2015-01-13T19:24:23.094Z - warn: [Entity] Unknown entity type, id=xxxxxxxxxxxxxxxxxxxx, type=undefined

Entity.coffee contains the following code.

            if data.type is 'portal'
                createPortalEntity id, timestamp, data, callback
            else if data.type is 'region'
                createFieldEntity id, timestamp, data, callback
            else if data.type is 'edge'
                createLinkEntity id, timestamp, data, callback
            else
                logger.warn "[Entity] Unknown entity type, id=#{id}, type=#{data.type}"
                callback && callback()

It seems it is the same prob iitc got three days ago:

10th January 2015

IITC 0.20.0 released. This is a critical update to fix loading of portals/links/fields after a protocol change by Niantic.

http://iitc.jonatkins.com/

Does anybody know how to fix this?

**Comment by mrcerf** [comment]
that is what i added into entity.coffee (only for portals)
1. into the "Add" method:
  data = remap data


2. end of file
+        
+types = {
+    'p' : 'portal'
+    'r' : 'region'
+    'e' : 'edge'
+}
+        
+teams = {
+    'E' : 'ENLIGHTENED'
+    'R' : 'RESISTANCE'
+    'N' : 'NEUTRAL'
+}
+    
+remap = (data) ->
+#TODO: links and fields
+    result = {
+        type: types[data[0]]
+        team: teams[data[1]]
+        latE6: data[2]
+        lngE6: data[3]
+        level: data[4]
+        health: data[5]
+        resCount: data[6]
+        image: data[7]
+        title: data[8]
+        ornaments: data[9]
+    }
+    result.mods = data[10] if data[10]
+    result.resonators = data[11] if data[11]
+    result.owner = data[12] if data[12]
+    return result
+

**Comment by danizwam** [comment]
I had the same idea, but i didn't know the correct format and how to do this ;) 

Nice work btw :D

I'll give it a try when i'm at home

**Comment by danizwam** [comment]
I have trouble merging your changes without a tool ;) I got an error with "main -->". Could you please post your new entity.coffee?

**Comment by mrcerf** [comment]
my entity.coffee has a lot of other changes.
but as error says, just check your indentation according to coffeescript idea

**Comment by danizwam** [comment]
I'm not that much into coffee.. I'm more into java and javascript. So i compiled the entitiy.js without remapping and added data = remap(data); manually.

>add: function(id, timestamp, data, callback) {
>      var main;
>	  data = remap(data);
>     main = function() {
>      Entity.entityCount++;
>     if (data.type === 'portal') {
>      return createPortalEntity(id, timestamp, data, callback);
>   } else if (data.type === 'region') {
>    return createFieldEntity(id, timestamp, data, callback);
>        } else if (data.type === 'edge') {
>          return createLinkEntity(id, timestamp, data, callback);
>        } else {
>          logger.warn("[Entity] Unknown entity type, id=" + id + ", type=" + data.type);
>          return callback && callback();
>        }
>      };

I don't know why, but adding "data = remap data" to the entitiy.coffee always causes a compile error.
The script runs now flawless and my database has been updated ;)

If you have a lot of more changes in your entity.coffee, does that mean you're maintaining the project now?

**Comment by mrcerf** [comment]
no, more like personal additions.
i also suggest we remove our spam comments

**Comment by danizwam** [comment]
What do you mean?

I've added every change suggested by you without "data = remap data" and compiled the entity.js. Then i added "data = rempa(data);" to the entity.js.
Did i miss something?

**Comment by mrcerf** [comment]
in order for details scan to work
```
@@ -80,27 +82,39 @@ Entity = GLOBAL.Entity =
                 callback()

             onSuccess: (response, callback) ->
+                response = remap response.result

                 if response.capturedTime?
                     response.capturedTime = parseInt response.capturedTime
```

**Comment by sn0opy** [comment]
The whole file with the applied diff: https://gist.github.com/sn0opy/37f0b1fe40f5cf6f5910

**Comment by sasha2002** [comment]
@sn0opy can you help me with this ? 
https://github.com/breeswish/sh-enl-ingress-intel-chat-bot
I integrate ingress-exporter that work very well as single app, but when i try to make a diff mungedetector.coffee and another files, i got for now this :
# node build/app.js --debug true
2015-01-27T18:37:36.710Z - info: [argv] --debug true

/somedir/build/lib/requestfactory.js:13
  delayedRequestQueue = new delayedQueue(function(task) {
                        ^
TypeError: object is not a function
    at Object.<anonymous> (/somedir/build/lib/requestfactory.js:13:25)
    at Object.<anonymous> (/somedir/build/lib/requestfactory.js:291:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/somedir/build/lib/mungedetector.js:6:20)
    at Object.<anonymous> (/somedir/build/lib/mungedetector.js:216:4)
